# Generated by Django 4.0.6 on 2024-03-31 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hz174', models.FileField(upload_to='audio/')),
                ('hz285', models.FileField(upload_to='audio/')),
                ('hz396', models.FileField(upload_to='audio/')),
                ('hz417', models.FileField(upload_to='audio/')),
                ('hz528', models.FileField(upload_to='audio/')),
                ('hz639', models.FileField(upload_to='audio/')),
                ('hz741', models.FileField(upload_to='audio/')),
                ('hz852', models.FileField(upload_to='audio/')),
                ('hz963', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('credentialId', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('reader', "I'm a Reader"), ('writer', "I'm a Writer")], max_length=20)),
                ('security_key', models.CharField(default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userId', models.CharField(db_column='userId', max_length=255, primary_key=True, serialize=False)),
                ('profileName', models.CharField(default='', max_length=128)),
                ('about', models.TextField(default='')),
                ('credentialId', models.ForeignKey(db_column='credentialId', on_delete=django.db.models.deletion.CASCADE, to='tales.usercredentials', to_field='credentialId')),
            ],
        ),
        migrations.CreateModel(
            name='Scribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('ebook', models.FileField(upload_to='documents/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('genre', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
                ('userId', models.ForeignKey(db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tales.userprofile')),
            ],
        ),
    ]
