# Generated by Django 4.0.6 on 2024-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
