# Generated by Django 4.0.6 on 2024-04-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0005_scribes_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedScribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scribeId', models.ForeignKey(db_column='scribeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tales.scribes')),
                ('userId', models.ForeignKey(db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tales.userprofile')),
            ],
        ),
    ]
